// Code generated by protoc-gen-go.
// source: pages.proto
// DO NOT EDIT!

/*
Package pages is a generated protocol buffer package.

It is generated from these files:
	pages.proto

It has these top-level messages:
	Empty
	Account
	Session
	RegisterRequest
	ConnectRequest
	PageGetRequest
	PageCreateRequest
	PageUpdateRequest
	PageDeleteRequest
	Page
	PagesSet
*/
package pages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Account struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Created  int64  `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	Modified int64  `protobuf:"varint,6,opt,name=modified" json:"modified,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Session struct {
	Account *Account `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Token   string   `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Session) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type RegisterRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ConnectRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Password   string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *ConnectRequest) Reset()                    { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string            { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()               {}
func (*ConnectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type PageGetRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *PageGetRequest) Reset()                    { *m = PageGetRequest{} }
func (m *PageGetRequest) String() string            { return proto.CompactTextString(m) }
func (*PageGetRequest) ProtoMessage()               {}
func (*PageGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type PageCreateRequest struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *PageCreateRequest) Reset()                    { *m = PageCreateRequest{} }
func (m *PageCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*PageCreateRequest) ProtoMessage()               {}
func (*PageCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type PageUpdateRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
}

func (m *PageUpdateRequest) Reset()                    { *m = PageUpdateRequest{} }
func (m *PageUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*PageUpdateRequest) ProtoMessage()               {}
func (*PageUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type PageDeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *PageDeleteRequest) Reset()                    { *m = PageDeleteRequest{} }
func (m *PageDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*PageDeleteRequest) ProtoMessage()               {}
func (*PageDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type Page struct {
	Id       string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Account  *Account `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Text     string   `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	Created  int64    `protobuf:"varint,4,opt,name=created" json:"created,omitempty"`
	Modified int64    `protobuf:"varint,5,opt,name=modified" json:"modified,omitempty"`
}

func (m *Page) Reset()                    { *m = Page{} }
func (m *Page) String() string            { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()               {}
func (*Page) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Page) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type PagesSet struct {
	Pages []*Page `protobuf:"bytes,1,rep,name=pages" json:"pages,omitempty"`
	Total int64   `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
	Page  int64   `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
}

func (m *PagesSet) Reset()                    { *m = PagesSet{} }
func (m *PagesSet) String() string            { return proto.CompactTextString(m) }
func (*PagesSet) ProtoMessage()               {}
func (*PagesSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PagesSet) GetPages() []*Page {
	if m != nil {
		return m.Pages
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*Account)(nil), "Account")
	proto.RegisterType((*Session)(nil), "Session")
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*ConnectRequest)(nil), "ConnectRequest")
	proto.RegisterType((*PageGetRequest)(nil), "PageGetRequest")
	proto.RegisterType((*PageCreateRequest)(nil), "PageCreateRequest")
	proto.RegisterType((*PageUpdateRequest)(nil), "PageUpdateRequest")
	proto.RegisterType((*PageDeleteRequest)(nil), "PageDeleteRequest")
	proto.RegisterType((*Page)(nil), "Page")
	proto.RegisterType((*PagesSet)(nil), "PagesSet")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Accounts service

type AccountsClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*Session, error)
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*Session, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*Session, error) {
	out := new(Session)
	err := grpc.Invoke(ctx, "/Accounts/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*Session, error) {
	out := new(Session)
	err := grpc.Invoke(ctx, "/Accounts/Connect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Accounts service

type AccountsServer interface {
	Register(context.Context, *RegisterRequest) (*Session, error)
	Connect(context.Context, *ConnectRequest) (*Session, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Accounts/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Accounts/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Accounts_Register_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _Accounts_Connect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

// Client API for Pages service

type PagesClient interface {
	PageCreate(ctx context.Context, in *PageCreateRequest, opts ...grpc.CallOption) (*Page, error)
	PageUpdate(ctx context.Context, in *PageUpdateRequest, opts ...grpc.CallOption) (*Page, error)
	PageDelete(ctx context.Context, in *PageDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
	PageGet(ctx context.Context, in *PageGetRequest, opts ...grpc.CallOption) (*Page, error)
	PageList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PagesSet, error)
}

type pagesClient struct {
	cc *grpc.ClientConn
}

func NewPagesClient(cc *grpc.ClientConn) PagesClient {
	return &pagesClient{cc}
}

func (c *pagesClient) PageCreate(ctx context.Context, in *PageCreateRequest, opts ...grpc.CallOption) (*Page, error) {
	out := new(Page)
	err := grpc.Invoke(ctx, "/Pages/PageCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pagesClient) PageUpdate(ctx context.Context, in *PageUpdateRequest, opts ...grpc.CallOption) (*Page, error) {
	out := new(Page)
	err := grpc.Invoke(ctx, "/Pages/PageUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pagesClient) PageDelete(ctx context.Context, in *PageDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/Pages/PageDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pagesClient) PageGet(ctx context.Context, in *PageGetRequest, opts ...grpc.CallOption) (*Page, error) {
	out := new(Page)
	err := grpc.Invoke(ctx, "/Pages/PageGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pagesClient) PageList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PagesSet, error) {
	out := new(PagesSet)
	err := grpc.Invoke(ctx, "/Pages/PageList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pages service

type PagesServer interface {
	PageCreate(context.Context, *PageCreateRequest) (*Page, error)
	PageUpdate(context.Context, *PageUpdateRequest) (*Page, error)
	PageDelete(context.Context, *PageDeleteRequest) (*Empty, error)
	PageGet(context.Context, *PageGetRequest) (*Page, error)
	PageList(context.Context, *Empty) (*PagesSet, error)
}

func RegisterPagesServer(s *grpc.Server, srv PagesServer) {
	s.RegisterService(&_Pages_serviceDesc, srv)
}

func _Pages_PageCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagesServer).PageCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pages/PageCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagesServer).PageCreate(ctx, req.(*PageCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pages_PageUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagesServer).PageUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pages/PageUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagesServer).PageUpdate(ctx, req.(*PageUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pages_PageDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagesServer).PageDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pages/PageDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagesServer).PageDelete(ctx, req.(*PageDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pages_PageGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagesServer).PageGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pages/PageGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagesServer).PageGet(ctx, req.(*PageGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pages_PageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagesServer).PageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pages/PageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagesServer).PageList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pages_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Pages",
	HandlerType: (*PagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PageCreate",
			Handler:    _Pages_PageCreate_Handler,
		},
		{
			MethodName: "PageUpdate",
			Handler:    _Pages_PageUpdate_Handler,
		},
		{
			MethodName: "PageDelete",
			Handler:    _Pages_PageDelete_Handler,
		},
		{
			MethodName: "PageGet",
			Handler:    _Pages_PageGet_Handler,
		},
		{
			MethodName: "PageList",
			Handler:    _Pages_PageList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("pages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 577 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x94, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0x65, 0xbb, 0x8e, 0xdd, 0xc9, 0x4f, 0xc9, 0x2f, 0x2b, 0x44, 0x2d, 0x53, 0x50, 0xb4,
	0x1c, 0x88, 0x2a, 0xb1, 0x91, 0x02, 0x12, 0x52, 0x4f, 0x94, 0x50, 0x71, 0xe9, 0x01, 0x5c, 0x21,
	0xce, 0x26, 0x1e, 0xac, 0x15, 0x89, 0xd7, 0x78, 0x37, 0x82, 0x5e, 0x11, 0x6f, 0x80, 0x78, 0x12,
	0x1e, 0x85, 0x57, 0xe0, 0x41, 0xd0, 0xfe, 0x71, 0xe2, 0xa4, 0xcd, 0xcd, 0xb3, 0x3b, 0xf3, 0x9d,
	0xef, 0xec, 0x7c, 0x64, 0xe8, 0xd7, 0x79, 0x89, 0x92, 0xd5, 0x8d, 0x50, 0x22, 0x3d, 0x2d, 0x85,
	0x28, 0x97, 0x38, 0xcd, 0x6b, 0x3e, 0xcd, 0xab, 0x4a, 0xa8, 0x5c, 0x71, 0x51, 0xb9, 0x5b, 0x1a,
	0x41, 0x78, 0xb9, 0xaa, 0xd5, 0x0d, 0xbd, 0x81, 0xe8, 0x62, 0xb1, 0x10, 0xeb, 0x4a, 0x91, 0x01,
	0xf8, 0xbc, 0x48, 0xbc, 0xb1, 0x37, 0x39, 0xce, 0x7c, 0x5e, 0x10, 0x02, 0x47, 0x55, 0xbe, 0xc2,
	0xc4, 0x37, 0x27, 0xe6, 0x9b, 0xdc, 0x83, 0x10, 0x57, 0x39, 0x5f, 0x26, 0x81, 0x39, 0xb4, 0x01,
	0x49, 0x20, 0x5a, 0x34, 0x98, 0x2b, 0x2c, 0x92, 0x70, 0xec, 0x4d, 0x82, 0xac, 0x0d, 0x49, 0x0a,
	0xf1, 0x4a, 0x14, 0xfc, 0x13, 0xc7, 0x22, 0xe9, 0x99, 0xab, 0x4d, 0x4c, 0xe7, 0x10, 0x5d, 0xa3,
	0x94, 0x5c, 0x54, 0x84, 0x42, 0x94, 0x5b, 0x17, 0xa6, 0x7f, 0x7f, 0x16, 0x33, 0xe7, 0x2a, 0x6b,
	0x2f, 0x74, 0x6b, 0x25, 0x3e, 0x63, 0xe5, 0xfc, 0xd8, 0x80, 0x7e, 0x80, 0x61, 0x86, 0x25, 0x97,
	0x0a, 0x9b, 0x0c, 0xbf, 0xac, 0x51, 0xaa, 0x8d, 0x6f, 0xef, 0x2e, 0xdf, 0x7e, 0xd7, 0x77, 0x0a,
	0x71, 0x9d, 0x4b, 0xf9, 0x55, 0x34, 0x85, 0x1b, 0x68, 0x13, 0xd3, 0x2b, 0x18, 0xcc, 0x45, 0x55,
	0xe1, 0x42, 0xb5, 0xba, 0x8f, 0x00, 0x78, 0x81, 0x95, 0xd2, 0xee, 0x1b, 0xa7, 0xde, 0x39, 0xd9,
	0x51, 0xf3, 0xf7, 0xd4, 0xc6, 0x30, 0x78, 0x9b, 0x97, 0xf8, 0x06, 0x37, 0x6a, 0x7b, 0xaf, 0x4d,
	0x9f, 0xc0, 0x48, 0x67, 0xcc, 0xcd, 0xc3, 0x75, 0x46, 0x51, 0xf8, 0x4d, 0xb5, 0xa3, 0xe8, 0x6f,
	0xfa, 0xc2, 0x26, 0xbe, 0xaf, 0x8b, 0x4e, 0xe2, 0x1d, 0xbb, 0x33, 0x85, 0x7e, 0xa7, 0xf0, 0xb1,
	0x2d, 0x7c, 0x8d, 0x4b, 0x3c, 0x58, 0x48, 0x7f, 0x78, 0x70, 0xa4, 0xb3, 0x6e, 0x29, 0x76, 0x56,
	0xe4, 0x1f, 0x5a, 0x51, 0xdb, 0x35, 0xd8, 0x76, 0xed, 0xb2, 0x71, 0x74, 0x98, 0x8d, 0x70, 0x8f,
	0x8d, 0x77, 0x10, 0x6b, 0x17, 0xf2, 0x1a, 0x15, 0x79, 0x00, 0xa1, 0x01, 0x3b, 0xf1, 0xc6, 0xc1,
	0xa4, 0x3f, 0x0b, 0x99, 0xbe, 0xc9, 0xec, 0x99, 0xa5, 0x42, 0xe5, 0x76, 0xb1, 0x41, 0x66, 0x03,
	0x6d, 0x44, 0x5f, 0x1b, 0x23, 0x41, 0x66, 0xbe, 0x67, 0xbf, 0x3c, 0x88, 0x9d, 0x63, 0x49, 0x2e,
	0x21, 0x6e, 0xb1, 0x21, 0xff, 0xb3, 0x3d, 0x82, 0xd2, 0x98, 0x39, 0x30, 0xe9, 0xc3, 0xef, 0x7f,
	0xfe, 0xfe, 0xf4, 0x4f, 0x28, 0x99, 0xba, 0x19, 0x25, 0x6b, 0x5c, 0xf2, 0xb9, 0x77, 0x46, 0x5e,
	0x41, 0xe4, 0x20, 0x21, 0x43, 0xb6, 0x8b, 0x4b, 0x47, 0xe4, 0xd4, 0x88, 0xdc, 0xa7, 0xa3, 0xad,
	0xc8, 0xc2, 0xe6, 0x9e, 0x7b, 0x67, 0xb3, 0xdf, 0x3e, 0x84, 0x66, 0x56, 0xf2, 0x12, 0x60, 0x8b,
	0x00, 0x21, 0xec, 0x16, 0x0f, 0xa9, 0x9d, 0x9d, 0x9e, 0x18, 0xc1, 0x11, 0xfd, 0x6f, 0xaa, 0x27,
	0x63, 0xf6, 0x41, 0xb5, 0x1f, 0xa7, 0x60, 0xd9, 0x70, 0x0a, 0x3b, 0xa0, 0x1c, 0x50, 0x58, 0x9b,
	0x1c, 0xad, 0x70, 0x61, 0x15, 0x2c, 0x24, 0x4e, 0x61, 0x87, 0x98, 0xb4, 0xc7, 0xec, 0x9f, 0x63,
	0x4f, 0xa2, 0x30, 0x49, 0x5a, 0xe2, 0x39, 0x44, 0x8e, 0x75, 0x32, 0x64, 0xbb, 0xd4, 0xb7, 0xed,
	0x47, 0xa6, 0xb6, 0x4f, 0x8e, 0x6d, 0x6d, 0x89, 0x8a, 0x3c, 0xb5, 0x1b, 0xbf, 0xe2, 0x52, 0x11,
	0xd7, 0x22, 0x3d, 0x66, 0x2d, 0x04, 0x74, 0x60, 0x2a, 0x62, 0xd2, 0x33, 0x15, 0xf2, 0x63, 0xcf,
	0xfc, 0xc7, 0x9e, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x1f, 0xdf, 0xf1, 0xf4, 0x04, 0x00,
	0x00,
}
